### ISSUE TITLE
使用HAdobe5k_2048.pth复现的结果比较奇怪

### ISSUE THREAD

**Issue by Git-oNmE** [bcmi/CDTNet-High-Resolution-Image-Harmonization#12]
您好，非常棒的工作！

我想要用这个模型对custom image做推理，所以我按照
```
python3 evaluate_model.py CDTNet ./HAdobe5k_2048.pth --gpu 0 --datasets HAdobe5k --hr 2048 --lr 512 --save_dir ./CDTNet_2048_result
```
来进行测试。

我只测试了一张图，也就是说，`HAdobe5k_test.txt`里面只包含：
```
a3630_1_5.jpg
a3630_1_1.jpg
a3630_1_2.jpg
a3630_1_3.jpg
a3630_1_4.jpg
```

测试出来后指标结果如图：
![image](https://github.com/bcmi/CDTNet-High-Resolution-Image-Harmonization/assets/29742421/c9245e53-e79f-4712-b569-78c74c020fdd)
图片结果的效果也比较差。

感觉自己是不是哪里设置错了，请问是我加载的模型不对吗？

**Comment by taoxinhao13** [comment]
您好，感谢您对我们工作的支持，我按您的跑了一下，结果是合理的。您可以稍微检查一下，可能是您LUT那边没有配置好，就会出现代码能运行但LUT结果完全不对的情况，从而使得最后结果很奇怪
![image](https://github.com/bcmi/CDTNet-High-Resolution-Image-Harmonization/assets/56617678/dba0480b-c93c-46c5-8aae-27f22d89e6cd)

**Comment by Git-oNmE** [comment]
> 您好，感谢您对我们工作的支持，我按您的跑了一下，结果是合理的。您可以稍微检查一下，可能是您LUT那边没有配置好，就会出现代码能运行但LUT结果完全不对的情况，从而使得最后结果很奇怪 ![image](https://user-images.githubusercontent.com/56617678/260627502-dba0480b-c93c-46c5-8aae-27f22d89e6cd.png)

我尝试按照`iSSAM`和`3D LUT`的说明来配置了环境（iSSAM就是安装了一下requirement.txt，LUT就是进Image-Adaptive-3DLUT/trilinear_cpp里面运行sh setup.sh），但是仍然没有效果。

实际上，如果我运行bash test.sh，会报错：
```
./CDTNet_2048_result
/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/datasets/HAdobe5k
Testing on HAdobe5k:   0%|                                                                                                                                                                                                                                                                 | 0/5 [00:00<?, ?it/s]/home/hlf/miniconda3/envs/BLIP2/lib/python3.8/site-packages/torch/nn/functional.py:3060: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
Testing on HAdobe5k:   0%|                                                                                                                                                                                                                                                                 | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "evaluate_model.py", line 106, in <module>
    main()
  File "evaluate_model.py", line 93, in main
    evaluate_dataset(dataset, predictor, dataset_metrics, logger, save_dir)
  File "/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/iharm/inference/evaluation.py", line 15, in evaluate_dataset
    pred = predictor.predict(sample['image'], sample_mask, return_numpy=False) # H,W,C
  File "/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/iharm/inference/predictor.py", line 39, in predict
    predicted_outs = self.net(image,mask)
  File "/home/hlf/miniconda3/envs/BLIP2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/iharm/model/base/cdt_net_model.py", line 116, in forward
    lut_output = self.lut(intermediates, image, mask)
  File "/home/hlf/miniconda3/envs/BLIP2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/iharm/model/modeling/lut.py", line 291, in forward
    gen_A0 = self.LUT0(image)
  File "/home/hlf/miniconda3/envs/BLIP2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/iharm/model/modeling/lut.py", line 361, in forward
    _, output = self.TrilinearInterpolation(self.LUT, x)
  File "/home/hlf/miniconda3/envs/BLIP2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/iharm/model/modeling/lut.py", line 434, in forward
    return TrilinearInterpolationFunction.apply(lut, x)
  File "/media/data3/hlf_data/CDTNet/CDTNet-High-Resolution-Image-Harmonization/iharm/model/modeling/lut.py", line 391, in forward
    assert 1 == trilinear.forward(lut, 
AttributeError: module 'trilinear' has no attribute 'forward'
```

问题正是出在iharm/model/modeling/lut.py：
```
class TrilinearInterpolationFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, lut, x):
        x = x.contiguous()

        output = x.new(x.size())
        dim = lut.size()[-1]
        shift = dim ** 3
        binsize = 1.000001 / (dim-1)
        W = x.size(2)
        H = x.size(3)
        batch = x.size(0)
        
        # ----------------------------------------------
        assert 1 == trilinear.forward(lut, 
                                      x, 
                                      output,
                                      dim, 
                                      shift, 
                                      binsize, 
                                      W, 
                                      H, 
                                      batch)
        # ---------------------------------------------

        int_package = torch.IntTensor([dim, shift, W, H, batch])
        float_package = torch.FloatTensor([binsize])
        variables = [lut, x, int_package, float_package]
        
        ctx.save_for_backward(*variables)
        
        return lut, output
```

显然如您所说，是LUT没有配置好。但是不知道该怎么配置？3D LUT里面所说的步骤我都做过了，而且没有报错。

**Comment by taoxinhao13** [comment]
您好，我刚才又尝试了一下，我pip uninstall trilinear，然后又重新安装了一遍，然后也没有发现类似问题，您可以conda list一下我想看一下您trilinear的版本，以及安装时的日志

**Comment by Git-oNmE** [comment]
解决问题了！为以后同样问题的人详述解决过程。

一开始我conda list，出来的版本是：
```
trilinear                 2.1                      pypi_0    pypi
```

然后按照您说的，pip uninstall trilinear，然后在CDTNet-High-Resolution-Image-Harmonization/trilinear_cpp里面执行`sh setup.sh`，版本就变成了：
```
trilinear                 0.0.0                    pypi_0    pypi
```

最后，用`sh test.sh`来运行脚本，就可以了。

**Comment by Git-oNmE** [comment]
> 解决问题了！为以后同样问题的人详述解决过程。
> 
> 一开始我conda list，出来的版本是：
> 
> ```
> trilinear                 2.1                      pypi_0    pypi
> ```
> 
> 然后按照您说的，pip uninstall trilinear，然后在CDTNet-High-Resolution-Image-Harmonization/trilinear_cpp里面执行`sh setup.sh`，版本就变成了：
> 
> ```
> trilinear                 0.0.0                    pypi_0    pypi
> ```
> 
> 最后，用`sh test.sh`来运行脚本，就可以了。

编译时可能遇到`fatal error: THC/THC.h: No such file or directory`，这是因为你的torch版本太高（一般1.6比较好，太高的版本把这个文件删去了）。不需要调整pytorch版本，直接调到对应的引用位置，全部注释掉即可。

**Comment by Vensss** [comment]
> > 解决问题了！为以后同样问题的人详述解决过程。
> > 一开始我conda list，出来的版本是：
> > ```
> > trilinear                 2.1                      pypi_0    pypi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后按照您说的，pip uninstall trilinear，然后在CDTNet-High-Resolution-Image-Harmonization/trilinear_cpp里面执行`sh setup.sh`，版本就变成了：
> > ```
> > trilinear                 0.0.0                    pypi_0    pypi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后，用`sh test.sh`来运行脚本，就可以了。
> 
> 编译时可能遇到`fatal error: THC/THC.h: No such file or directory`，这是因为你的torch版本太高（一般1.6比较好，太高的版本把这个文件删去了）。不需要调整pytorch版本，直接调到对应的引用位置，全部注释掉即可。

在`trilinear_cpp/src/trilinear_kernel.h`和`trilinear_cpp/src/trilinear_cuda.cpp`中注释了对应的`#include <THC/THC.h>`，但我仍遇到`getCurrentCUDAStream() is not a member of at::cuda`（pytorch==1.13.1），解决方式是：

```cpp
//#include <THE/THC.h>
//Replace with
#include <ATen/cuda/CUDAContext.h>
#include <ATen/cuda/CUDAEvent.h>
```
